import DashboardLayout from "@/components/DashboardLayout";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";
import { BookOpen, Bot, FileText, Plus, UserPlus, Users, Settings2, MessageCircle, ArrowUpRight } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";

export default function HRDashboard() {
  const { user } = useAuth();
  const access = trpc.access.me.useQuery(undefined, { retry: false });
  const companyId = access.data?.companyId ?? 4;
  const recruitment = trpc.hr.recruitment.useQuery({ companyId }, { enabled: Boolean(companyId) });
  const knowledge = trpc.hr.knowledge.useQuery({ companyId }, { enabled: Boolean(companyId) });
  const assistant = trpc.hr.assistantPreview.useQuery({ companyId }, { enabled: Boolean(companyId) });
  const soon = (label: string) => toast.info(`${label} estará disponible en la siguiente fase.`);
  const candidates = recruitment.data ?? [];
  const docs = knowledge.data ?? [];
  const displayName = user?.email === "alexa.torres@people-ai.test" ? user.name : "Alexa Torres";
  return <DashboardLayout roleOverride="HR"><div className="mx-auto max-w-7xl space-y-7">
    <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-blue-600">PEOPLE AI · Talento Humano</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Buenos días, {displayName}</h1><p className="mt-2 text-sm text-slate-500">Este es el centro de gestión de Talento Humano de PEOPLE AI.</p></div><Badge className="w-fit border-0 bg-blue-50 px-3 py-1.5 text-blue-700">Empresa Demo — Talento Humano</Badge></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[{label:"Procesos de contratación",value:candidates.length || "08",caption:"Procesos activos",icon:UserPlus,color:"text-blue-600 bg-blue-50"},{label:"Documentos pendientes",value:candidates.length ? candidates.reduce((sum,c)=>sum+(c.documentsRequired-c.documentsReceived),0) : "14",caption:"Documentos por recibir",icon:FileText,color:"text-amber-600 bg-amber-50"},{label:"Procesos completos",value:candidates.filter(c=>c.status==="complete").length || "05",caption:"Listos para revisión",icon:Users,color:"text-teal-600 bg-teal-50"},{label:"Consultas al asistente",value:"142",caption:"Consultas atendidas · demo",icon:Bot,color:"text-violet-600 bg-violet-50"}].map(item=><Card key={item.label} className="border-slate-200/80 shadow-sm"><CardContent className="p-5"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${item.color}`}><item.icon className="h-5 w-5" /></div><p className="mt-5 text-sm text-slate-500">{item.label}</p><p className="mt-1 text-3xl font-semibold tracking-tight">{item.value}</p><p className="mt-1 text-xs text-slate-400">{item.caption}</p></CardContent></Card>)}</div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]">
      <Card className="border-slate-200/80 shadow-sm"><CardHeader className="flex flex-row items-start justify-between border-b border-slate-100"><div><CardTitle className="flex items-center gap-2 text-base"><FileText className="h-4 w-4 text-blue-600" />Contratación</CardTitle><p className="mt-1 text-xs text-slate-500">Acompaña cada proceso hasta tener su expediente listo.</p></div><Button size="sm" onClick={() => soon("Nueva contratación")} className="bg-slate-950 text-white"><Plus className="mr-1 h-3.5 w-3.5" />Nueva contratación</Button></CardHeader><CardContent className="p-0"><div className="hidden grid-cols-[1.3fr_1fr_0.6fr_0.7fr] gap-3 border-b border-slate-100 px-5 py-3 text-[10px] font-semibold uppercase tracking-wider text-slate-400 sm:grid"><span>Candidato</span><span>Cargo</span><span>Documentos</span><span>Estado</span></div>{recruitment.isLoading ? <div className="space-y-3 p-5"><Skeleton className="h-12 w-full" /><Skeleton className="h-12 w-full" /></div> : recruitment.error ? <p className="p-6 text-sm text-rose-600">No se pudo cargar contratación para este tenant.</p> : candidates.length ? candidates.map(candidate=><div key={candidate.id} className="grid gap-2 border-b border-slate-100 px-5 py-4 text-sm sm:grid-cols-[1.3fr_1fr_0.6fr_0.7fr] sm:items-center"><span className="font-medium text-slate-800">{candidate.candidateName}</span><span className="text-slate-500">{candidate.position}</span><span className="text-slate-500">{candidate.documentsReceived}/{candidate.documentsRequired}</span><Badge variant="outline" className="w-fit">{candidate.status === "complete" ? "Completo" : "Pendiente"}</Badge></div>) : <div className="p-8 text-center"><p className="text-sm font-medium text-slate-700">Aún no hay procesos registrados</p><p className="mt-1 text-xs text-slate-400">La lista se mostrará cuando se cree el primer proceso.</p></div>}<div className="flex justify-end p-4"><Button variant="ghost" size="sm" onClick={() => soon("Ver contrataciones")} className="text-xs">Ver contrataciones <ArrowUpRight className="ml-1 h-3.5 w-3.5" /></Button></div></CardContent></Card>
      <Card className="overflow-hidden border-0 bg-slate-950 text-white shadow-xl"><CardContent className="relative p-6"><div className="absolute -right-12 -top-12 h-40 w-40 rounded-full bg-blue-500/20 blur-3xl" /><div className="relative"><div className="flex items-center justify-between"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white/10"><Bot className="h-5 w-5 text-blue-200" /></div><Badge className="border-0 bg-white/10 text-blue-100">Demo</Badge></div><h2 className="mt-5 text-xl font-semibold">PEOPLE AI Assistant</h2><p className="mt-2 text-sm leading-6 text-slate-300">Responde preguntas frecuentes utilizando la información oficial de la empresa.</p><div className="mt-5 space-y-3 rounded-xl border border-white/10 bg-white/5 p-4 text-sm"><p className="text-slate-400">Colaborador</p><p>¿Cómo solicito un certificado laboral?</p><div className="flex gap-2 border-t border-white/10 pt-3"><Bot className="mt-0.5 h-4 w-4 shrink-0 text-teal-300" /><p className="text-slate-300">{assistant.isLoading ? "Consultando la demo…" : assistant.data?.content || "Puedes solicitarlo desde el canal habilitado de Talento Humano."}</p></div></div><Button onClick={() => soon("HR Assistant")} className="mt-5 w-full border border-white/15 bg-white/10 text-white hover:bg-white/20"><MessageCircle className="mr-2 h-4 w-4" />Probar HR Assistant</Button></div></CardContent></Card>
    </div>
    <div className="grid gap-6 xl:grid-cols-[1fr_0.8fr]"><Card className="border-slate-200/80 shadow-sm"><CardHeader className="flex flex-row items-start justify-between"><div><CardTitle className="flex items-center gap-2 text-base"><BookOpen className="h-4 w-4 text-violet-600" />Base de conocimiento</CardTitle><p className="mt-1 text-xs text-slate-500">Información que posteriormente utilizará el asistente.</p></div><Button variant="outline" size="sm" onClick={() => soon("Agregar documento")}><Plus className="mr-1 h-3.5 w-3.5" />Agregar documento</Button></CardHeader><CardContent>{knowledge.isLoading ? <Skeleton className="h-16 w-full" /> : knowledge.error ? <p className="text-sm text-rose-600">No se pudo cargar la base de conocimiento.</p> : docs.length ? <div className="grid gap-3 sm:grid-cols-2">{docs.map(doc=><button key={doc.id} onClick={() => soon(doc.title)} className="flex items-center gap-3 rounded-xl border border-dashed border-slate-200 p-3 text-left transition hover:border-violet-300 hover:bg-violet-50/40"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-50"><BookOpen className="h-4 w-4 text-violet-600" /></div><div><p className="text-sm font-medium text-slate-700">{doc.title}</p><p className="text-xs text-slate-400">{doc.category}</p></div></button>)}</div> : <p className="py-5 text-center text-sm text-slate-500">No hay documentos demo disponibles.</p>}</CardContent></Card><Card className="border-slate-200/80 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2 className="h-4 w-4 text-slate-600" />Canales e integraciones</CardTitle><p className="mt-1 text-xs text-slate-500">Un mismo asistente, varios canales futuros.</p></CardHeader><CardContent className="space-y-2">{[["Web","Disponible","bg-teal-500"],["WhatsApp","Próximamente","bg-amber-400"],["Microsoft Teams","Próximamente","bg-amber-400"]].map(([name,status,dot])=><div key={name} className="flex items-center justify-between rounded-xl bg-slate-50 px-3 py-3"><span className="text-sm font-medium text-slate-700">{name}</span><span className="flex items-center gap-2 text-xs text-slate-500"><i className={`h-2 w-2 rounded-full ${dot}`} />{status}</span></div>)}</CardContent></Card></div>
  </div></DashboardLayout>;
}
