import { and, asc, desc, eq, inArray } from "drizzle-orm";
import { createHash, randomBytes } from "node:crypto";
import { auditLogs, candidateAccessLinks, candidateDocuments, candidateProfiles, companies, documentTemplateItems, documentTemplates, hiringProcesses, hiringRequirements, internalNotifications, jobPositions } from "../drizzle/schema";
import { getDb } from "./db";
import { storageGetSignedUrl, storagePut } from "./storage";

export const MAX_FILE_BYTES = 10 * 1024 * 1024;
export const ALLOWED_MIME_TYPES = new Set(["application/pdf", "image/jpeg", "image/png"]);
const MIME_EXTENSIONS: Record<string, string[]> = { "application/pdf": ["pdf"], "image/jpeg": ["jpg", "jpeg"], "image/png": ["png"] };
export const hashToken = (token: string) => createHash("sha256").update(token).digest("hex");
export const isLinkUsable = (status: string, expiresAt: Date, now = Date.now()) => status === "active" && expiresAt.getTime() >= now;
export const getMissingRequirements = (requirements: Array<{ required: boolean; status: string }>) => requirements.filter(req => req.required && !["uploaded", "replaced", "verified"].includes(req.status));
export const normalize = (title: string, original: string) => `${title.replace(/[^a-zA-Z0-9áéíóúÁÉÍÓÚñÑ ]/g, "").trim()}.${original.split(".").pop()?.toLowerCase() || "bin"}`;
export const hasMagicSignature = (bytes: Uint8Array, mimeType: string) => { if (mimeType === "application/pdf") return new TextDecoder().decode(bytes.slice(0, 5)) === "%PDF-"; if (mimeType === "image/jpeg") return bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff; if (mimeType === "image/png") return bytes.slice(0, 8).every((byte, index) => byte === [137, 80, 78, 71, 13, 10, 26, 10][index]); return false; };
export const isValidUpload = (originalName: string, mimeType: string, sizeBytes: number, bytes?: Uint8Array) => { const extension = originalName.split(".").pop()?.toLowerCase() || ""; return ALLOWED_MIME_TYPES.has(mimeType) && Boolean(MIME_EXTENSIONS[mimeType]?.includes(extension)) && sizeBytes <= MAX_FILE_BYTES && (!bytes || hasMagicSignature(bytes, mimeType)); };
async function audit(companyId: number, action: string, metadata: Record<string, unknown>, userId?: number) { const db = await getDb(); if (db) await db.insert(auditLogs).values({ companyId, userId, action, module: "hiring", result: "success", metadata: JSON.stringify(metadata) }); }

export async function listPositions(companyId: number) { const db = await getDb(); if (!db) return []; return db.select().from(jobPositions).where(eq(jobPositions.companyId, companyId)).orderBy(asc(jobPositions.name)); }
export async function createPosition(companyId: number, name: string, description?: string, userId?: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const result = await db.insert(jobPositions).values({ companyId, name, description: description || null }); const id = Number(result[0].insertId); await audit(companyId, "job_position_created", { id, name }, userId); return id; }
export async function listTemplates(companyId: number) { const db = await getDb(); if (!db) return []; return db.select().from(documentTemplates).where(and(eq(documentTemplates.companyId, companyId), eq(documentTemplates.status, "active"))).orderBy(desc(documentTemplates.updatedAt)); }
export async function getTemplate(companyId: number, templateId: number) { const db = await getDb(); if (!db) return null; const template = (await db.select().from(documentTemplates).where(and(eq(documentTemplates.companyId, companyId), eq(documentTemplates.id, templateId))).limit(1))[0]; if (!template) return null; const items = await db.select().from(documentTemplateItems).where(and(eq(documentTemplateItems.companyId, companyId), eq(documentTemplateItems.templateId, templateId))).orderBy(asc(documentTemplateItems.sortOrder)); return { ...template, items }; }
export async function createTemplate(companyId: number, positionId: number, name: string, items: Array<{ title: string; description?: string; required: boolean; sortOrder: number }>, userId?: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const position = (await db.select().from(jobPositions).where(and(eq(jobPositions.id, positionId), eq(jobPositions.companyId, companyId))).limit(1))[0]; if (!position) throw new Error("Position not found"); const result = await db.insert(documentTemplates).values({ companyId, positionId, name }); const templateId = Number(result[0].insertId); if (items.length) await db.insert(documentTemplateItems).values(items.map(item => ({ ...item, companyId, templateId }))); await audit(companyId, "document_template_created", { templateId, positionId }, userId); return getTemplate(companyId, templateId); }
export async function updateTemplate(companyId: number, templateId: number, items: Array<{ title: string; description?: string; required: boolean; sortOrder: number }>, userId?: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const template = await getTemplate(companyId, templateId); if (!template) throw new Error("Template not found"); await db.delete(documentTemplateItems).where(and(eq(documentTemplateItems.companyId, companyId), eq(documentTemplateItems.templateId, templateId))); if (items.length) await db.insert(documentTemplateItems).values(items.map(item => ({ ...item, companyId, templateId }))); await audit(companyId, "document_template_updated", { templateId }, userId); return getTemplate(companyId, templateId); }
export async function listHiring(companyId: number) { const db = await getDb(); if (!db) return []; const processes = await db.select().from(hiringProcesses).where(eq(hiringProcesses.companyId, companyId)).orderBy(desc(hiringProcesses.createdAt)); return Promise.all(processes.map(async process => { const detail = await getHiringDetail(companyId, process.id); return { ...process, candidateName: detail?.candidate?.fullName || "Candidato", positionName: detail?.position?.name || "Cargo", requiredCount: detail?.requirements.filter(r => r.required).length || 0, receivedCount: detail?.requirements.filter(r => ["uploaded", "replaced", "verified"].includes(r.status)).length || 0 }; })); }
export async function createHiring(companyId: number, userId: number, input: { fullName: string; identificationNumber: string; email: string; positionId: number; templateId: number }) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const template = await getTemplate(companyId, input.templateId); if (!template || template.positionId !== input.positionId) throw new Error("Template not found"); const candidateResult = await db.insert(candidateProfiles).values({ companyId, fullName: input.fullName, identificationNumber: input.identificationNumber, email: input.email }); const candidateId = Number(candidateResult[0].insertId); const processResult = await db.insert(hiringProcesses).values({ companyId, candidateId, positionId: input.positionId, templateId: input.templateId, createdByUserId: userId, status: "pending" }); const processId = Number(processResult[0].insertId); await db.insert(hiringRequirements).values(template.items.map(item => ({ companyId, processId, sourceTemplateItemId: item.id, title: item.title, description: item.description, required: item.required, sortOrder: item.sortOrder }))); await audit(companyId, "hiring_process_created", { processId, candidateId }, userId); return getHiringDetail(companyId, processId); }
export async function getHiringDetail(companyId: number, processId: number) { const db = await getDb(); if (!db) return null; const process = (await db.select().from(hiringProcesses).where(and(eq(hiringProcesses.companyId, companyId), eq(hiringProcesses.id, processId))).limit(1))[0]; if (!process) return null; const candidate = (await db.select().from(candidateProfiles).where(and(eq(candidateProfiles.companyId, companyId), eq(candidateProfiles.id, process.candidateId))).limit(1))[0]; const position = (await db.select().from(jobPositions).where(and(eq(jobPositions.companyId, companyId), eq(jobPositions.id, process.positionId))).limit(1))[0]; const company = (await db.select().from(companies).where(eq(companies.id, companyId)).limit(1))[0]; const requirements = await db.select().from(hiringRequirements).where(and(eq(hiringRequirements.companyId, companyId), eq(hiringRequirements.processId, processId))).orderBy(asc(hiringRequirements.sortOrder)); const documents = await db.select().from(candidateDocuments).where(and(eq(candidateDocuments.companyId, companyId), eq(candidateDocuments.processId, processId), eq(candidateDocuments.status, "active"))); return { process, candidate, position, company, requirements, documents }; }
export async function updateRequirement(companyId: number, processId: number, requirementId: number, patch: { title?: string; required?: boolean; status?: "pending" | "uploaded" | "replaced" | "removed" | "verified" }, userId?: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(hiringRequirements).set(patch).where(and(eq(hiringRequirements.companyId, companyId), eq(hiringRequirements.processId, processId), eq(hiringRequirements.id, requirementId))); await audit(companyId, "hiring_requirement_updated", { processId, requirementId }, userId); return getHiringDetail(companyId, processId); }
export async function generateLink(companyId: number, processId: number, userId?: number) { const db = await getDb(); if (!db) throw new Error("Database unavailable"); const detail = await getHiringDetail(companyId, processId); if (!detail) throw new Error("Hiring process not found"); await db.update(candidateAccessLinks).set({ status: "revoked", revokedAt: new Date() }).where(and(eq(candidateAccessLinks.companyId, companyId), eq(candidateAccessLinks.processId, processId), eq(candidateAccessLinks.status, "active"))); const token = randomBytes(32).toString("base64url"); await db.insert(candidateAccessLinks).values({ companyId, processId, candidateId: detail.process.candidateId, tokenHash: hashToken(token), expiresAt: new Date(Date.now() + 7 * 86400000) }); await audit(companyId, "candidate_link_generated", { processId }, userId); return { token, expiresAt: new Date(Date.now() + 7 * 86400000) }; }
export async function getPortal(token: string) { const db = await getDb(); if (!db) return null; const link = (await db.select().from(candidateAccessLinks).where(eq(candidateAccessLinks.tokenHash, hashToken(token))).limit(1))[0]; if (!link || !isLinkUsable(link.status, link.expiresAt)) return null; await db.update(candidateAccessLinks).set({ lastUsedAt: new Date() }).where(eq(candidateAccessLinks.id, link.id)); const detail = await getHiringDetail(link.companyId, link.processId); return detail ? { ...detail, linkId: link.id, expiresAt: link.expiresAt } : null; }
export async function uploadPortalDocument(token: string, requirementId: number, originalName: string, mimeType: string, bytes: Uint8Array) { if (!isValidUpload(originalName, mimeType, bytes.byteLength, bytes)) throw new Error("Archivo inválido: formato, contenido o tamaño no permitido"); const portal = await getPortal(token); if (!portal) throw new Error("Enlace no disponible"); const requirement = portal.requirements.find(item => item.id === requirementId); if (!requirement) throw new Error("Requisito no encontrado"); const normalizedName = normalize(requirement.title, originalName); const key = `candidate-documents/${portal.process.companyId}/${portal.process.id}/${requirement.id}-${randomBytes(12).toString("hex")}-${normalizedName}`; const stored = await storagePut(key, Buffer.from(bytes), mimeType); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(candidateDocuments).set({ status: "removed" }).where(and(eq(candidateDocuments.companyId, portal.process.companyId), eq(candidateDocuments.requirementId, requirementId), eq(candidateDocuments.processId, portal.process.id), eq(candidateDocuments.status, "active"))); await db.insert(candidateDocuments).values({ companyId: portal.process.companyId, processId: portal.process.id, requirementId, originalName, normalizedName, fileKey: stored.key, mimeType, sizeBytes: bytes.byteLength }); await db.update(hiringRequirements).set({ status: "uploaded" }).where(and(eq(hiringRequirements.companyId, portal.process.companyId), eq(hiringRequirements.id, requirementId))); await audit(portal.process.companyId, "candidate_document_uploaded", { processId: portal.process.id, requirementId, normalizedName }); return getPortal(token); }
export async function removePortalDocument(token: string, requirementId: number) { const portal = await getPortal(token); if (!portal) throw new Error("Enlace no disponible"); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(candidateDocuments).set({ status: "removed" }).where(and(eq(candidateDocuments.companyId, portal.process.companyId), eq(candidateDocuments.processId, portal.process.id), eq(candidateDocuments.requirementId, requirementId), eq(candidateDocuments.status, "active"))); await db.update(hiringRequirements).set({ status: "removed" }).where(and(eq(hiringRequirements.companyId, portal.process.companyId), eq(hiringRequirements.processId, portal.process.id), eq(hiringRequirements.id, requirementId))); await audit(portal.process.companyId, "candidate_document_removed", { processId: portal.process.id, requirementId }); return getPortal(token); }
export async function listNotifications(companyId: number, recipientUserId: number) { const db = await getDb(); if (!db) return []; return db.select().from(internalNotifications).where(and(eq(internalNotifications.companyId, companyId), eq(internalNotifications.recipientUserId, recipientUserId))).orderBy(desc(internalNotifications.createdAt)); }
export async function getDocumentUrl(companyId: number, processId: number, documentId: number) { const db = await getDb(); if (!db) return null; const document = (await db.select().from(candidateDocuments).where(and(eq(candidateDocuments.companyId, companyId), eq(candidateDocuments.processId, processId), eq(candidateDocuments.id, documentId), eq(candidateDocuments.status, "active"))).limit(1))[0]; return document ? storageGetSignedUrl(document.fileKey) : null; }
export async function submitPortal(token: string) { const portal = await getPortal(token); if (!portal) throw new Error("Enlace no disponible"); const missing = getMissingRequirements(portal.requirements); if (missing.length) throw new Error(`Faltan ${missing.length} documentos obligatorios`); const db = await getDb(); if (!db) throw new Error("Database unavailable"); await db.update(hiringProcesses).set({ status: "in_review" }).where(and(eq(hiringProcesses.companyId, portal.process.companyId), eq(hiringProcesses.id, portal.process.id))); await db.update(candidateAccessLinks).set({ status: "completed" }).where(eq(candidateAccessLinks.id, portal.linkId)); await db.insert(internalNotifications).values({ companyId: portal.process.companyId, recipientUserId: portal.process.createdByUserId, processId: portal.process.id, type: "candidate_submission_sent", title: `${portal.candidate?.fullName || "El candidato"} completó su documentación.` }); await audit(portal.process.companyId, "candidate_submission_sent", { processId: portal.process.id }); return getPortal(token); }
